version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: local_postgres
    environment:
      POSTGRES_USER: domir
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: domivium
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: local_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass domivium_redis_2024
    volumes:
      - redisdata:/data
    networks:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:

networks:
  backend:
    driver: bridge
