// <auto-generated>
using MasterMemory;
using MessagePack;

namespace Domivium.Client.Data.Row
{
	[MemoryTable("character"), MessagePackObject(true)]
	public class CharacterRow
	{
		[PrimaryKey] public int Id { get; set; }
		public string Job { get; set; } = string.Empty;
		public int Health { get; set; }
		public int Attack { get; set; }
		public int Defense { get; set; }
		public int AttackRange { get; set; }
		public int Speed { get; set; }
		public int CriticalRate { get; set; } // permyriad
		public int CriticalDamage { get; set; } // permyriad
	}
}
// </auto-generated>
