// <auto-generated>
using MasterMemory;
using MessagePack;

namespace Domivium.Client.Data.Row
{
	[MemoryTable("foodbox"), MessagePackObject(true)]
	public class FoodBoxRow
	{
		[PrimaryKey] public int Id { get; set; }
		[SecondaryKey(0), NonUnique] public int GroupId { get; set; }
		public string ItemType { get; set; } = string.Empty;
		public int ItemId { get; set; }
		public int MinCount { get; set; }
		public int MaxCount { get; set; }
		public int DropRate { get; set; } // percent
	}
}
// </auto-generated>
