// <auto-generated>
using MasterMemory;
using MessagePack;

namespace Domivium.Client.Data.Row
{
	[MemoryTable("loot"), MessagePackObject(true)]
	public class LootRow
	{
		[PrimaryKey] public int Id { get; set; }
		[SecondaryKey(0), NonUnique] public int GroupId { get; set; }
		public string Type { get; set; } = string.Empty;
		public int TypeId { get; set; }
		public int Amount { get; set; }
		public int DropRate { get; set; } // percent
	}
}
// </auto-generated>
