// <auto-generated>
using MasterMemory;
using MessagePack;

namespace Domivium.Client.Data.Row
{
	[MemoryTable("monster"), MessagePackObject(true)]
	public class MonsterRow
	{
		[PrimaryKey] public int Id { get; set; }
		public string Job { get; set; } = string.Empty;
		public int Health { get; set; }
		public int Attack { get; set; }
		public int Defense { get; set; }
		public int AttackRange { get; set; }
		public int Speed { get; set; }
	}
}
// </auto-generated>
