using System;
using System.Collections.Generic;
using Domivium.Client.Core.UI;
using UnityEngine;

namespace Domivium.Client.Editor
{
    public static class EditorConfig
    {
        // Namespace suffixes
        private const string CoreUISuffix = ".Core.UI";
        private const string ContentsUISuffix = ".Contents.UI";

        // File extensions
        public const string CSharpExtension = ".cs";
        public const string PrefabExtension = ".prefab";

        public const string Id = "Id";
        public const string UI = "UI";
        public const string Presenter = "Presenter";
        public const string PrefabSearchPattern = "*.prefab";

        // Folder paths
        private const string ResourcesFolderName = "Resources";
        private const string ScriptsFolderName = "Scripts";
        private const string ContentsFolderName = "Contents";
        private const string GeneratedFolderName = "Generated";

        // Generated code markers
        public const string StartGenerate = "// <auto-generated>";
        public const string EndGenerate = "// </auto-generated>";

        private static readonly string System = typeof(Type).Namespace;
        private static readonly string SystemGeneric = typeof(Dictionary<,>).Namespace;
        private static readonly string Core = typeof(UIConfig).Namespace;

        private static string RootPath => Application.dataPath;
        private static string Contents => Core.Replace(CoreUISuffix, ContentsUISuffix);

        public static readonly string NamespaceGenerated = $"namespace {Contents}.Generated";
        public static readonly string NamespaceContentsStatic = $"namespace {Contents}.{UIConfig.Static}";
        public static readonly string NamespaceContentsStack = $"namespace {Contents}.{UIConfig.Stack}";
        public static readonly string NamespaceContentsSystem = $"namespace {Contents}.{UIConfig.System}";

        public static readonly string UsingSystem = $"using {System};";
        public static readonly string UsingGeneric = $"using {SystemGeneric};";
        public static readonly string UsingCore = $"using {Core};";
        public static readonly string UsingView = $"using {Core}.View;";
        public static readonly string UsingNavigation = $"using {Core}.Navigation;";
        public static readonly string UsingPresenter = $"using {Core}.Presenter;";

        public static readonly string UsingContentsStatic = $"using {Contents}.{UIConfig.Static};";
        public static readonly string UsingContentsStack = $"using {Contents}.{UIConfig.Stack};";
        public static readonly string UsingContentsSystem = $"using {Contents}.{UIConfig.System};";

        public static readonly string ResourcesPath = $"{RootPath}/{ResourcesFolderName}";
        public static readonly string GeneratedPath = $"{RootPath}/{ScriptsFolderName}/{ContentsFolderName}/{UI}/{GeneratedFolderName}";

        public static readonly string MappingStaticClass = $"public static class {UIConfig.UIMapping}";
        public static readonly string MappingDictionary = $"public static readonly Dictionary<{nameof(UIId)}, ({nameof(Type)} type, {nameof(String)} prefabPath)> UI = new()";

        public enum UIType
        {
            Static,
            Stack,
            System
        }

        public static string ToUIId(KeyValuePair<string, int> kvp)
        {
            return $"public static UIId {kvp.Key} = {kvp.Value};";
        }

        public static string ToClass(UIType uiType)
        {
            return $"public static class {uiType.ToString()}{UI}{Id}";
        }

        public static string ToUsing(UIType uiType)
        {
            return uiType switch
            {
                UIType.Static => UsingContentsStatic,
                UIType.Stack => UsingContentsStack,
                UIType.System => UsingContentsSystem,
                _ => throw new ArgumentOutOfRangeException(nameof(uiType))
            };
        }

        public static string ToContentsNamespace(this UIType uiType)
        {
            return uiType switch
            {
                UIType.Static => NamespaceContentsStatic,
                UIType.Stack => NamespaceContentsStack,
                UIType.System => NamespaceContentsSystem,
                _ => throw new ArgumentOutOfRangeException(nameof(uiType), uiType, null)
            };
        }

        public static string ToPath(this UIType uiType)
        {
            return uiType switch
            {
                UIType.Static => $"{RootPath}/{ScriptsFolderName}/{ContentsFolderName}/{UI}/{UIConfig.Static}",
                UIType.Stack => $"{RootPath}/{ScriptsFolderName}/{ContentsFolderName}/{UI}/{UIConfig.Stack}",
                UIType.System => $"{RootPath}/{ScriptsFolderName}/{ContentsFolderName}/{UI}/{UIConfig.System}",
                _ => throw new ArgumentOutOfRangeException(nameof(uiType), uiType, null)
            };
        }

        public static string ToPresenter(this UIType uiType, string prefix = "")
        {
            return $"{prefix}{uiType}{UI}{Presenter}";
        }

        public static string ToView(this UIType uiType, string prefix = "")
        {
            return $"{prefix}{uiType}{UI}View";
        }

        public static string ToMessage(this UIType uiType, string prefix)
        {
            return $"I{prefix}{uiType}{UI}Message";
        }
    }
}