using System;
using System.Collections.Generic;
using System.IO;
using Domivium.Client.Core.Audio;
using Domivium.Client.Core.UI;
using UnityEngine;

namespace Domivium.Client.Editor
{
    public static class EditorConfig
    {
        // Namespace suffixes
        private const string Csv = "Csv";
        private const string Row = "Row";

        // File extensions
        public const string CSVExtension = ".csv";
        public const string CSharpExtension = ".cs";
        public const string PrefabExtension = ".prefab";

        // Folder names
        private const string DataFolderName = "Data";

        private const string AudioFolderName = "Audio";
        private const string ScriptsFolderName = "Scripts";
        private const string PrefabsFolderName = "Prefabs";
        private const string ContentsFolderName = "Contents";
        private const string EditorFolderName = "Editor";
        private const string TemplatesFolderName = "Templates";
        private const string GeneratedFolderName = "Generated";

        //Keys
        public const string MasterDBSessionKey = "MASTER_DB_EDITOR_SESSION";
        public const string TypeSessionKey = "UI_EDITOR_SESSION_TYPE";
        public const string NameSessionKey = "UI_EDITOR_SESSION_NAME";
        public const string TypePrefsKey = "UI_EDITOR_PREFS_UI_TYPE";
        public const string NamePrefsKey = "UI_EDITOR_PREFS_UI_NAME";

        // Generated code markers
        public const string StartGenerate = "// <auto-generated>";
        public const string EndGenerate = "// </auto-generated>";

        public const string ApplicationScene = "Assets/Scenes/Application.unity";
        public const string WorkspaceScene = "Assets/Scenes/Workspace.unity";
        public const string UIContainer = "Assets/ScriptableObjects/UIContainer.asset";
        public const string AudioContainer = "Assets/ScriptableObjects/AudioContainer.asset";
        public const string ConfigContainer = "Assets/ScriptableObjects/ConfigContainer.asset";

        public const string UI = "UI";
        public const string Audio = "Audio";
        public const string UIIds = "UIIds";
        public const string AudioIds = "AudioIds";
        public const string UIMapping = "UIMapping";
        public const string AudioMapping = "AudioMapping";

        private static readonly string System = typeof(Type).Namespace;
        private static readonly string SystemGeneric = typeof(Dictionary<,>).Namespace;
        private static readonly string UICore = typeof(UIId).Namespace;
        private static readonly string AudioCore = typeof(AudioId).Namespace;

        private static string RootPath => Application.dataPath;

        public static string UIPrefabRootPath => Path.Combine(RootPath, PrefabsFolderName, UI);

        public static string MasterDBPath => Path.Combine(RootPath, DataFolderName, "MasterDB.bytes");
        public static string CsvRootPath => Path.Combine(RootPath, DataFolderName, Csv);
        public static string RowDataRootPath => Path.Combine(RootPath, ScriptsFolderName, DataFolderName, Row);
        public static string RowDataNamespace => "Domivium.Client.Data.Row";

        private static string UIContents => UICore.Replace(".Core.UI", ".Contents.UI");
        private static string AudioContents => AudioCore.Replace(".Core.Audio", ".Contents.Audio");

        public static readonly string UINamespaceGenerated = $"namespace {UIContents}.Generated";
        public static readonly string AudioNamespaceGenerated = $"namespace {AudioContents}.Generated";

        public static readonly string UsingSystem = $"using {System};";
        public static readonly string UsingGeneric = $"using {SystemGeneric};";
        public static readonly string UsingUICore = $"using {UICore};";
        public static readonly string UsingAudioCore = $"using {AudioCore};";

        public static readonly string UIMappingClass = $"public static class {UIMapping}";
        public static readonly string AudioMappingClass = $"public static class {AudioMapping}";

        public static readonly string UIMappingDictionary = $"public static readonly Dictionary<{nameof(UIId)}, ({nameof(Type)} presenter, {nameof(Type)} view)> UI = new()";
        public static readonly string AudioMappingDictionary = $"public static readonly Dictionary<{nameof(AudioId)}, string> Names = new()";

        public static string GetContentsNamespaceName(UIType uiType)
        {
            var nsDecl = $"namespace {UIContents}.{uiType.ToString()}";
            const string keyword = "namespace ";
            if (nsDecl.StartsWith(keyword, StringComparison.Ordinal))
                return nsDecl.Substring(keyword.Length);

            return nsDecl;
        }

        public static string ToAudioResourcePath(this AudioParam param) => Path.Combine(RootPath, AudioFolderName, param.AsPrimitive());

        public static string ToScriptPath(this UIType uiType)
        {
            var typeFolder = uiType switch
            {
                UIType.Static => UIConfig.Static,
                UIType.Stack => UIConfig.Stack,
                UIType.System => UIConfig.System,
                _ => throw new ArgumentOutOfRangeException(nameof(uiType), uiType, null)
            };
            return Path.Combine(RootPath, ScriptsFolderName, ContentsFolderName, UI, typeFolder);
        }

        public static string ToPrefabPath(this UIType uiType)
        {
            var typeFolder = uiType switch
            {
                UIType.Static => UIConfig.Static,
                UIType.Stack => UIConfig.Stack,
                UIType.System => UIConfig.System,
                _ => throw new ArgumentOutOfRangeException(nameof(uiType), uiType, null)
            };
            return Path.Combine(RootPath, PrefabsFolderName, UI, typeFolder);
        }

        public static string ToPresenter(this UIType uiType, string prefix = "") => $"{prefix}{uiType}{UI}Presenter";

        public static string ToView(this UIType uiType, string prefix = "") => $"{prefix}{uiType}{UI}View";

        public static string ToMessage(this UIType uiType, string prefix) => $"I{prefix}{uiType}{UI}Message";

        public static string GetGeneratedScriptPath(string folderName, string scriptName) => Path.Combine(RootPath, ScriptsFolderName, ContentsFolderName, folderName, GeneratedFolderName, $"{scriptName}{CSharpExtension}");

        public static string ToAssetsRelative(string absolutePath)
        {
            var projectRoot = Directory.GetParent(RootPath)!.FullName.Replace("\\", "/");
            var normalized = absolutePath.Replace("\\", "/");
            return !normalized.StartsWith(projectRoot) ? absolutePath : normalized[(projectRoot.Length + 1)..];
        }

        public static string GetTemplatePath(string kind, UIType uiType)
        {
            var fileName = $"{kind}.{uiType}.txt";
            return Path.Combine(RootPath, ScriptsFolderName, EditorFolderName, TemplatesFolderName, UI, fileName);
        }
    }
}