using System;
using System.Collections.Generic;
using System.IO;
using Domivium.Client.Core.UI;
using UnityEngine;

namespace Domivium.Client.Editor
{
    public static class EditorConfig
    {
        // Namespace suffixes
        private const string CoreUISuffix = ".Core.UI";
        private const string ContentsUISuffix = ".Contents.UI";
        private const string UI = "UI";

        // File extensions
        public const string CSharpExtension = ".cs";
        public const string PrefabExtension = ".prefab";

        // Folder names
        private const string ScriptsFolderName = "Scripts";
        private const string PrefabsFolderName = "Prefabs";
        private const string ContentsFolderName = "Contents";
        private const string EditorFolderName = "Editor";
        private const string TemplatesFolderName = "Templates";
        private const string GeneratedFolderName = "Generated";

        //Keys
        public const string TypeSessionKey = "UI_EDITOR_SESSION_TYPE";
        public const string NameSessionKey = "UI_EDITOR_SESSION_NAME";
        public const string TypePrefsKey = "UI_EDITOR_PREFS_UI_TYPE";
        public const string NamePrefsKey = "UI_EDITOR_PREFS_UI_NAME";

        // Generated code markers
        public const string StartGenerate = "// <auto-generated>";
        public const string EndGenerate = "// </auto-generated>";

        public const string Workspace = "Assets/Scenes/UIWorkspace.unity";
        public const string UIContainer = "Assets/ScriptableObjects/UIContainer.asset";

        public const string UIId = "UIId";

        private static readonly string System = typeof(Type).Namespace;
        private static readonly string SystemGeneric = typeof(Dictionary<,>).Namespace;
        private static readonly string Core = typeof(UIConfig).Namespace;

        private static string RootPath => Application.dataPath;

        public static string PrefabRootPath => Path.Combine(RootPath, PrefabsFolderName, UI);

        private static string Contents => Core.Replace(CoreUISuffix, ContentsUISuffix);

        public static readonly string NamespaceGenerated = $"namespace {Contents}.Generated";
        public static readonly string UsingSystem = $"using {System};";
        public static readonly string UsingGeneric = $"using {SystemGeneric};";
        public static readonly string UsingCore = $"using {Core};";

        public static readonly string MappingStaticClass = $"public static class {UIConfig.UIMapping}";
        public static readonly string MappingDictionary = $"public static readonly Dictionary<{nameof(UIId)}, ({nameof(Type)} presenter, {nameof(Type)} view)> UI = new()";


        public static string GetContentsNamespaceName(UIType uiType)
        {
            var nsDecl = $"namespace {Contents}.{uiType.ToString()}";
            const string keyword = "namespace ";
            if (nsDecl.StartsWith(keyword, StringComparison.Ordinal))
                return nsDecl.Substring(keyword.Length);

            return nsDecl;
        }

        public static string ToScriptPath(this UIType uiType)
        {
            var typeFolder = uiType switch
            {
                UIType.Static => UIConfig.Static,
                UIType.Stack => UIConfig.Stack,
                UIType.System => UIConfig.System,
                _ => throw new ArgumentOutOfRangeException(nameof(uiType), uiType, null)
            };
            return Path.Combine(RootPath, ScriptsFolderName, ContentsFolderName, UI, typeFolder);
        }

        public static string ToPrefabPath(this UIType uiType)
        {
            var typeFolder = uiType switch
            {
                UIType.Static => UIConfig.Static,
                UIType.Stack => UIConfig.Stack,
                UIType.System => UIConfig.System,
                _ => throw new ArgumentOutOfRangeException(nameof(uiType), uiType, null)
            };
            return Path.Combine(RootPath, PrefabsFolderName, UI, typeFolder);
        }

        public static string ToPresenter(this UIType uiType, string prefix = "")
        {
            return $"{prefix}{uiType}{UI}Presenter";
        }

        public static string ToView(this UIType uiType, string prefix = "")
        {
            return $"{prefix}{uiType}{UI}View";
        }

        public static string ToMessage(this UIType uiType, string prefix)
        {
            return $"I{prefix}{uiType}{UI}Message";
        }

        public static string GetScriptPath(string scriptName)
        {
            return Path.Combine(RootPath, ScriptsFolderName, ContentsFolderName, UI, GeneratedFolderName, $"{scriptName}{CSharpExtension}");
        }

        public static string ToAssetsRelative(string absolutePath)
        {
            var projectRoot = Directory.GetParent(RootPath)!.FullName.Replace("\\", "/");
            var normalized = absolutePath.Replace("\\", "/");
            return !normalized.StartsWith(projectRoot) ? absolutePath : normalized[(projectRoot.Length + 1)..];
        }

        public static string GetTemplatePath(string kind, UIType uiType)
        {
            var fileName = $"{kind}.{uiType}.txt";
            return Path.Combine(RootPath, ScriptsFolderName, EditorFolderName, TemplatesFolderName, UI, fileName);
        }
    }
}